dataset: Amazon_Kindle_Store
seed: 2020
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
load_col:
  inter: [user_id, item_id, rating]
  item: [item_id, categories]
val_interval:
  rating: "[1,inf)"
user_inter_num_interval: "[10,inf)"
item_inter_num_interval: "[10,inf)"

# training and evaluation
epochs: 500
train_batch_size: 4096
metrics: ["Recall", "MRR", "NDCG", "Hit","ItemCoverage"]
valid_metric: MRR@10
training_neg_sample_num: 1
topk: [10, 20, 50]
eval_batch_size: 1000000
store_idx : True

show_progress: False





